#!/bin/bash

set -e

# ===========================
# Clone this repo

# If this repo is not installed at your home, clone it

remote_repository_path=github.com/krzmknt/dotfiles
local_repository_path=~/ghq/$remote_repository_path
if [ ! -d $local_repository_path ]; then
  git clone https://$remote_repository_path $local_repository_path
fi
cd $local_repository_path

# ===========================
# Homebrew

# Check if Homebrew is installed
if ! command -v brew &>/dev/null; then
  echo "Homebrew is not installed. Installing now..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  # Configure environment variables (considering M1/M2 Macs)
  if [[ $(uname -m) == "arm64" ]]; then
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile
    eval "$($(brew --prefix)/bin/brew shellenv)"
  else
    echo 'eval "$(/usr/local/bin/brew shellenv)"' >> ~/.bash_profile
    eval "$($(brew --prefix)/bin/brew shellenv)"
  fi

  echo "Homebrew has been installed."
else
  echo "Homebrew is already installed."
fi

# Check for the existence of the Brewfile
BREWFILE="./Brewfile"
if [[ ! -f "$BREWFILE" ]]; then
  echo "Brewfile not found. Exiting script."
  exit 1
fi

# Update Homebrew
echo "Updating Homebrew..."
brew update

# Install packages based on the Brewfile
echo "Installing packages from Brewfile..."
brew bundle --file="$BREWFILE"

if [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Installing packages from Brewfile.mac..."
    brew bundle --file=Brewfile.mac
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Installing packages from Brewfile.linux..."
    brew bundle --file=Brewfile.linux
fi

# ===========================
# Stow

stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ fish
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ hammerspoon
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ karabiner
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ mise
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ nvim
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ peco
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ skhd
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ stackline
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ tmux
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ wezterm
stow -v -d ~/ghq/github.com/krzmknt/dotfiles/config -t ~ yabai

