#!/bin/bash

set -e

# ===========================
# Clone this repo
# ---------------------------
# If this repo is not installed at your home, clone it
if [ ! -d ~/dotfiles ]; then
  git clone https://github.com/krzmknt/dotfiles
fi


# ===========================
# Stow
# ---------------------------
stow -v -d ~/dotfiles/config -t ~ fish
stow -v -d ~/dotfiles/config -t ~ karabiner
stow -v -d ~/dotfiles/config -t ~ mise
stow -v -d ~/dotfiles/config -t ~ nvim
stow -v -d ~/dotfiles/config -t ~ peco
stow -v -d ~/dotfiles/config -t ~ skhd
stow -v -d ~/dotfiles/config -t ~ tmux
stow -v -d ~/dotfiles/config -t ~ wezterm
stow -v -d ~/dotfiles/config -t ~ yabai


# ===========================
# Fish
# ---------------------------
# If fish is not the default shell, change it
if [ ! $SHELL = `which fish` ]; then
  which fish | sudo tee -a /etc/shells
  chsh -s `which fish`
fi


# Install oh-my-fish
if [ ! -d ~/.local/share/omf ]; then
  curl https://raw.githubusercontent.com/oh-my-fish/oh-my-fish/master/bin/install | fish
  omf install peco
fi
