#!/bin/bash


which nvim >> /dev/null
if [[ $? -eq 0 ]]; then
  echo "Alreadly installed: nvim"
  exit
fi

curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
chmod u+x nvim.appimage
./nvim.appimage
if [[ $? -eq 1 ]];then
  ./nvim.appimage --appimage-extract
  ./squashfs-root/AppRun --version
  # Optional: exposing nvim globally.
  sudo mv squashfs-root /
  sudo ln -s /squashfs-root/AppRun /usr/bin/nvim
fi
rm -f ./nvim.appimage
